### PR TITLE
Added tailwind framework

### PR DESCRIPTION
**Pull request by WoodWalkerr**

### CODE REVIEW

**Comment by WoodWalkerr** [comment]
Please review this :)

**Comment by elyodivilas** [comment]
> 

Please add ticket in your commit Melvs :)

**Review by elyodivilas — CHANGES_REQUESTED** [review]
Please change the commit with ticket

**Comment by WoodWalkerr** [comment]
okay erp pwede na ba to?

**Review by elyodivilas — APPROVED** [review]

**Pull request merged**
